FROM node:22-alpine

WORKDIR /app

RUN mkdir -p node_modules
RUN npm install -g nodemon
RUN npm install -D tsx

COPY package*.json ./
COPY tsconfig.json ./

COPY . .

EXPOSE 8000

CMD ["nodemon", "--exec", "tsx", "server.ts"]